const pool = require("../config/db");
const bcrypt = require("bcryptjs");

const roles = {
    clinical: ["Admin", "Doctor", "Receptionist"],
    admin: ["Admin"],
    pharmacy: ["Admin", "Pharmacist"],
    laboratory: ["Admin", "Doctor", "Lab Technician"],
    billing: ["Admin", "Receptionist"]
};

const list = (table, id, columns, searchColumns = []) => async (req, res) => {
    try {
        const search = req.query.search;
        const params = [];
        let sql = `SELECT ${columns} FROM ${table}`;
        if (search && searchColumns.length) {
            sql += ` WHERE ${searchColumns.map(column => `${column} LIKE ?`).join(" OR ")}`;
            searchColumns.forEach(() => params.push(`%${search}%`));
        }
        sql += ` ORDER BY ${id} DESC`;
        const [rows] = await pool.query(sql, params);
        res.json({ count: rows.length, [table]: rows });
    } catch (error) {
        console.error(`List ${table} error:`, error);
        res.status(500).json({ message: `Failed to fetch ${table}` });
    }
};

const getById = (table, id, columns = "*") => async (req, res) => {
    try {
        const [rows] = await pool.query(`SELECT ${columns} FROM ${table} WHERE ${id} = ?`, [req.params.id]);
        if (!rows.length) return res.status(404).json({ message: `${table} record not found` });
        res.json(rows[0]);
    } catch (error) {
        console.error(`Get ${table} error:`, error);
        res.status(500).json({ message: `Failed to fetch ${table} record` });
    }
};

const doctorList = async (req, res) => {
    try {
        const search = req.query.search;
        const params = [];
        let sql = `SELECT d.*, dep.name AS department_name, u.username FROM doctors d LEFT JOIN departments dep ON dep.department_id = d.department_id LEFT JOIN users u ON u.user_id = d.user_id WHERE d.is_active = TRUE`;
        if (search) { sql += " AND (d.full_name LIKE ? OR d.specialization LIKE ? OR d.phone LIKE ? OR dep.name LIKE ?)"; params.push(`%${search}%`, `%${search}%`, `%${search}%`, `%${search}%`); }
        sql += " ORDER BY d.doctor_id DESC";
        const [doctors] = await pool.query(sql, params);
        res.json({ count: doctors.length, doctors });
    } catch (error) { console.error("List doctors error:", error); res.status(500).json({ message: "Failed to fetch doctors" }); }
};

const createDoctor = async (req, res) => {
    const { username, password, full_name, specialization, phone, email, department_id } = req.body;
    if (!username || !password || !full_name || !department_id) return res.status(400).json({ message: "Username, password, full name and department are required" });
    const connection = await pool.getConnection();
    try {
        await connection.beginTransaction();
        const passwordHash = await bcrypt.hash(password, 10);
        const [userResult] = await connection.query("INSERT INTO users (username, password_hash, role, is_active) VALUES (?, ?, 'Doctor', TRUE)", [username.trim(), passwordHash]);
        const [doctorResult] = await connection.query("INSERT INTO doctors (user_id, department_id, full_name, specialization, phone, email, is_active) VALUES (?, ?, ?, ?, ?, ?, TRUE)", [userResult.insertId, department_id, full_name.trim(), specialization || null, phone || null, email || null]);
        await connection.commit();
        res.status(201).json({ message: "Doctor created successfully", doctor_id: doctorResult.insertId, username });
    } catch (error) { await connection.rollback(); console.error("Create doctor error:", error); res.status(error.code === "ER_DUP_ENTRY" ? 409 : 500).json({ message: error.code === "ER_DUP_ENTRY" ? "Username already exists" : "Failed to create doctor" }); } finally { connection.release(); }
};

const updateDoctor = async (req, res) => {
    const { full_name, specialization, phone, email, department_id } = req.body;
    try { const [result] = await pool.query("UPDATE doctors SET full_name = ?, specialization = ?, phone = ?, email = ?, department_id = ? WHERE doctor_id = ? AND is_active = TRUE", [full_name, specialization || null, phone || null, email || null, department_id, req.params.id]); if (!result.affectedRows) return res.status(404).json({ message: "Doctor not found" }); res.json({ message: "Doctor updated successfully" }); }
    catch (error) { console.error("Update doctor error:", error); res.status(500).json({ message: "Failed to update doctor" }); }
};

const deactivateDoctor = async (req, res) => {
    const connection = await pool.getConnection();
    try { await connection.beginTransaction(); const [doctor] = await connection.query("SELECT user_id FROM doctors WHERE doctor_id = ? AND is_active = TRUE FOR UPDATE", [req.params.id]); if (!doctor.length) { await connection.rollback(); return res.status(404).json({ message: "Doctor not found" }); } await connection.query("UPDATE doctors SET is_active = FALSE WHERE doctor_id = ?", [req.params.id]); await connection.query("UPDATE users SET is_active = FALSE WHERE user_id = ?", [doctor[0].user_id]); await connection.commit(); res.json({ message: "Doctor deactivated successfully" }); }
    catch (error) { await connection.rollback(); console.error("Deactivate doctor error:", error); res.status(500).json({ message: "Failed to deactivate doctor" }); } finally { connection.release(); }
};

const appointmentList = async (req, res) => {
    try { const { search, status, date } = req.query; const params = []; let sql = "SELECT a.*, p.full_name AS patient_name, d.full_name AS doctor_name FROM appointments a JOIN patients p ON p.patient_id = a.patient_id JOIN doctors d ON d.doctor_id = a.doctor_id WHERE 1 = 1"; if (search) { sql += " AND (p.full_name LIKE ? OR d.full_name LIKE ? OR a.reason LIKE ?)"; params.push(`%${search}%`, `%${search}%`, `%${search}%`); } if (status) { sql += " AND a.status = ?"; params.push(status); } if (date) { sql += " AND a.appointment_date = ?"; params.push(date); } sql += " ORDER BY a.appointment_date DESC, a.appointment_time DESC"; const [appointments] = await pool.query(sql, params); res.json({ count: appointments.length, appointments }); }
    catch (error) { console.error("List appointments error:", error); res.status(500).json({ message: "Failed to fetch appointments" }); }
};

const createAppointment = async (req, res) => { const { patient_id, doctor_id, appointment_date, appointment_time, reason } = req.body; if (!patient_id || !doctor_id || !appointment_date || !appointment_time) return res.status(400).json({ message: "Patient, doctor, date and time are required" }); try { const [result] = await pool.query("INSERT INTO appointments (patient_id, doctor_id, appointment_date, appointment_time, reason, status) VALUES (?, ?, ?, ?, ?, 'Scheduled')", [patient_id, doctor_id, appointment_date, appointment_time, reason || null]); res.status(201).json({ message: "Appointment created successfully", appointment_id: result.insertId }); } catch (error) { console.error("Create appointment error:", error); res.status(500).json({ message: "Failed to create appointment" }); } };
const updateAppointmentStatus = async (req, res) => { const { status, appointment_date, appointment_time, reason } = req.body; const valid = ["Scheduled", "Completed", "Cancelled", "No Show"]; if (status && !valid.includes(status)) return res.status(400).json({ message: "Invalid appointment status" }); try { const [result] = await pool.query("UPDATE appointments SET status = COALESCE(?, status), appointment_date = COALESCE(?, appointment_date), appointment_time = COALESCE(?, appointment_time), reason = COALESCE(?, reason) WHERE appointment_id = ?", [status || null, appointment_date || null, appointment_time || null, reason || null, req.params.id]); if (!result.affectedRows) return res.status(404).json({ message: "Appointment not found" }); res.json({ message: "Appointment updated successfully" }); } catch (error) { console.error("Update appointment error:", error); res.status(500).json({ message: "Failed to update appointment" }); } };
const createConsultation = async (req, res) => { const { appointment_id, patient_id, doctor_id, consultation_date, diagnosis, notes } = req.body; if (!patient_id || !doctor_id || !diagnosis) return res.status(400).json({ message: "Patient, doctor and diagnosis are required" }); try { const [result] = await pool.query("INSERT INTO consultations (appointment_id, patient_id, doctor_id, consultation_date, diagnosis, notes) VALUES (?, ?, ?, COALESCE(?, CURRENT_DATE), ?, ?)", [appointment_id || null, patient_id, doctor_id, consultation_date || null, diagnosis, notes || null]); if (appointment_id) await pool.query("UPDATE appointments SET status = 'Completed' WHERE appointment_id = ?", [appointment_id]); res.status(201).json({ message: "Consultation created successfully", consultation_id: result.insertId }); } catch (error) { console.error("Create consultation error:", error); res.status(500).json({ message: "Failed to create consultation" }); } };
const updateConsultation = async (req, res) => { const { diagnosis, notes, consultation_date } = req.body; try { const [result] = await pool.query("UPDATE consultations SET diagnosis = ?, notes = ?, consultation_date = ? WHERE consultation_id = ?", [diagnosis, notes || null, consultation_date, req.params.id]); if (!result.affectedRows) return res.status(404).json({ message: "Consultation not found" }); res.json({ message: "Consultation updated successfully" }); } catch (error) { console.error("Update consultation error:", error); res.status(500).json({ message: "Failed to update consultation" }); } };
const createMedicalRecord = async (req, res) => { const { patient_id, doctor_id, consultation_id, visit_date, notes, vital_signs } = req.body; if (!patient_id || !doctor_id) return res.status(400).json({ message: "Patient and doctor are required" }); try { const [result] = await pool.query("INSERT INTO medical_records (patient_id, doctor_id, consultation_id, visit_date, notes, vital_signs) VALUES (?, ?, ?, COALESCE(?, CURRENT_DATE), ?, ?)", [patient_id, doctor_id, consultation_id || null, visit_date || null, notes || null, vital_signs || null]); res.status(201).json({ message: "Medical record created successfully", record_id: result.insertId }); } catch (error) { console.error("Create medical record error:", error); res.status(500).json({ message: "Failed to create medical record" }); } };

const prescriptionList = async (req, res) => { try { const [prescriptions] = await pool.query("SELECT pr.*, p.full_name AS patient_name, d.full_name AS doctor_name FROM prescriptions pr JOIN patients p ON p.patient_id = pr.patient_id JOIN doctors d ON d.doctor_id = pr.doctor_id ORDER BY pr.prescription_id DESC"); res.json({ count: prescriptions.length, prescriptions }); } catch (error) { console.error("List prescriptions error:", error); res.status(500).json({ message: "Failed to fetch prescriptions" }); } };
const createPrescription = async (req, res) => { const { patient_id, doctor_id, consultation_id, diagnosis, notes, items } = req.body; if (!patient_id || !doctor_id || !Array.isArray(items) || !items.length) return res.status(400).json({ message: "Patient, doctor and at least one medicine are required" }); const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [result] = await connection.query("INSERT INTO prescriptions (patient_id, doctor_id, consultation_id, prescription_date, diagnosis, notes) VALUES (?, ?, ?, CURRENT_DATE, ?, ?)", [patient_id, doctor_id, consultation_id || null, diagnosis || null, notes || null]); for (const item of items) await connection.query("INSERT INTO prescription_items (prescription_id, medicine_id, dosage, frequency, duration, quantity, instructions) VALUES (?, ?, ?, ?, ?, ?, ?)", [result.insertId, item.medicine_id, item.dosage || null, item.frequency || null, item.duration || null, item.quantity || 0, item.instructions || null]); await connection.commit(); res.status(201).json({ message: "Prescription created successfully", prescription_id: result.insertId }); } catch (error) { await connection.rollback(); console.error("Create prescription error:", error); res.status(500).json({ message: "Failed to create prescription" }); } finally { connection.release(); } };

const createSimple = (table, fields, required = []) => async (req, res) => { const missing = required.find(field => req.body[field] === undefined || req.body[field] === ""); if (missing) return res.status(400).json({ message: `${missing} is required` }); try { const values = fields.map(field => req.body[field] === undefined ? null : req.body[field]); const [result] = await pool.query(`INSERT INTO ${table} (${fields.join(", ")}) VALUES (${fields.map(() => "?").join(", ")})`, values); res.status(201).json({ message: `${table} record created successfully`, id: result.insertId }); } catch (error) { console.error(`Create ${table} error:`, error); res.status(error.code === "ER_DUP_ENTRY" ? 409 : 500).json({ message: error.code === "ER_DUP_ENTRY" ? "Duplicate record" : `Failed to create ${table} record` }); } };
const updateSimple = (table, idColumn, fields) => async (req, res) => { try { const values = fields.map(field => req.body[field] === undefined ? null : req.body[field]); values.push(req.params.id); const [result] = await pool.query(`UPDATE ${table} SET ${fields.map(field => `${field} = ?`).join(", ")} WHERE ${idColumn} = ?`, values); if (!result.affectedRows) return res.status(404).json({ message: "Record not found" }); res.json({ message: "Record updated successfully" }); } catch (error) { console.error(`Update ${table} error:`, error); res.status(500).json({ message: `Failed to update ${table} record` }); } };

const stockTransaction = async (req, res) => { const { medicine_id, batch_id, quantity, transaction_type, reference_id, remarks } = req.body; if (!medicine_id || !batch_id || !quantity || !["Stock In", "Dispensing"].includes(transaction_type)) return res.status(400).json({ message: "Medicine, batch, positive quantity and valid transaction type are required" }); const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [batches] = await connection.query("SELECT quantity, expiry_date FROM medicine_batches WHERE batch_id = ? AND medicine_id = ? FOR UPDATE", [batch_id, medicine_id]); if (!batches.length) { await connection.rollback(); return res.status(404).json({ message: "Batch not found" }); } if (transaction_type === "Dispensing" && new Date(batches[0].expiry_date) < new Date()) { await connection.rollback(); return res.status(409).json({ message: "Cannot dispense expired medicine" }); } const nextQuantity = transaction_type === "Stock In" ? batches[0].quantity + Number(quantity) : batches[0].quantity - Number(quantity); if (nextQuantity < 0) { await connection.rollback(); return res.status(409).json({ message: "Insufficient stock" }); } await connection.query("UPDATE medicine_batches SET quantity = ? WHERE batch_id = ?", [nextQuantity, batch_id]); const [result] = await connection.query("INSERT INTO medicine_transactions (medicine_id, batch_id, transaction_type, quantity, reference_id, remarks) VALUES (?, ?, ?, ?, ?, ?)", [medicine_id, batch_id, transaction_type, quantity, reference_id || null, remarks || null]); await connection.commit(); res.status(201).json({ message: "Stock transaction recorded successfully", transaction_id: result.insertId, remaining_quantity: nextQuantity }); } catch (error) { await connection.rollback(); console.error("Stock transaction error:", error); res.status(500).json({ message: "Failed to record stock transaction" }); } finally { connection.release(); } };
const admitPatient = async (req, res) => { const { patient_id, doctor_id, department_id, room_id, bed_id, admission_date, reason } = req.body; const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [beds] = await connection.query("SELECT status FROM beds WHERE bed_id = ? AND room_id = ? FOR UPDATE", [bed_id, room_id]); if (!beds.length) { await connection.rollback(); return res.status(404).json({ message: "Bed not found" }); } if (beds[0].status !== "Available") { await connection.rollback(); return res.status(409).json({ message: "Bed is not available" }); } const [result] = await connection.query("INSERT INTO admissions (patient_id, doctor_id, department_id, room_id, bed_id, admission_date, reason, status) VALUES (?, ?, ?, ?, ?, COALESCE(?, NOW()), ?, 'Admitted')", [patient_id, doctor_id, department_id, room_id, bed_id, admission_date || null, reason || null]); await connection.query("UPDATE beds SET status = 'Occupied' WHERE bed_id = ?", [bed_id]); await connection.commit(); res.status(201).json({ message: "Patient admitted successfully", admission_id: result.insertId }); } catch (error) { await connection.rollback(); console.error("Admission error:", error); res.status(500).json({ message: "Failed to admit patient" }); } finally { connection.release(); } };
const dischargePatient = async (req, res) => { const { diagnosis, discharge_summary, instructions, final_bill_status } = req.body; const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [admissions] = await connection.query("SELECT bed_id FROM admissions WHERE admission_id = ? AND status = 'Admitted' FOR UPDATE", [req.params.id]); if (!admissions.length) { await connection.rollback(); return res.status(404).json({ message: "Active admission not found" }); } await connection.query("INSERT INTO discharges (admission_id, discharge_date, diagnosis, discharge_summary, instructions, final_bill_status) VALUES (?, NOW(), ?, ?, ?, ?)", [req.params.id, diagnosis || null, discharge_summary || null, instructions || null, final_bill_status || "Pending"]); await connection.query("UPDATE admissions SET status = 'Discharged' WHERE admission_id = ?", [req.params.id]); await connection.query("UPDATE beds SET status = 'Available' WHERE bed_id = ?", [admissions[0].bed_id]); await connection.commit(); res.json({ message: "Patient discharged successfully" }); } catch (error) { await connection.rollback(); console.error("Discharge error:", error); res.status(500).json({ message: "Failed to discharge patient" }); } finally { connection.release(); } };
const createBill = async (req, res) => { const { patient_id, admission_id, items } = req.body; if (!patient_id || !Array.isArray(items) || !items.length) return res.status(400).json({ message: "Patient and bill items are required" }); const connection = await pool.getConnection(); try { await connection.beginTransaction(); let total = 0; const normalized = items.map(item => { const amount = Number(item.quantity) * Number(item.unit_price); total += amount; return { ...item, amount }; }); const [bill] = await connection.query("INSERT INTO bills (patient_id, admission_id, bill_date, total_amount, status, outstanding_amount) VALUES (?, ?, CURRENT_DATE, ?, 'Unpaid', ?)", [patient_id, admission_id || null, total, total]); for (const item of normalized) await connection.query("INSERT INTO bill_items (bill_id, service_type, reference_id, description, quantity, unit_price, amount) VALUES (?, ?, ?, ?, ?, ?, ?)", [bill.insertId, item.service_type, item.reference_id || null, item.description || null, item.quantity, item.unit_price, item.amount]); await connection.commit(); res.status(201).json({ message: "Bill created successfully", bill_id: bill.insertId, total_amount: total, outstanding_amount: total }); } catch (error) { await connection.rollback(); console.error("Create bill error:", error); res.status(500).json({ message: "Failed to create bill" }); } finally { connection.release(); } };
const recordPayment = async (req, res) => { const { amount, payment_method, reference_no, remarks } = req.body; if (!amount || Number(amount) <= 0) return res.status(400).json({ message: "A positive payment amount is required" }); const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [bills] = await connection.query("SELECT outstanding_amount FROM bills WHERE bill_id = ? FOR UPDATE", [req.params.id]); if (!bills.length) { await connection.rollback(); return res.status(404).json({ message: "Bill not found" }); } if (Number(amount) > Number(bills[0].outstanding_amount)) { await connection.rollback(); return res.status(409).json({ message: "Payment cannot exceed outstanding amount" }); } const outstanding = Number(bills[0].outstanding_amount) - Number(amount); await connection.query("INSERT INTO payments (bill_id, amount, payment_method, reference_no, remarks) VALUES (?, ?, ?, ?, ?)", [req.params.id, amount, payment_method || "Cash", reference_no || null, remarks || null]); await connection.query("UPDATE bills SET outstanding_amount = ?, status = ? WHERE bill_id = ?", [outstanding, outstanding === 0 ? "Paid" : "Partially Paid", req.params.id]); await connection.commit(); res.status(201).json({ message: "Payment recorded successfully", outstanding_amount: outstanding }); } catch (error) { await connection.rollback(); console.error("Payment error:", error); res.status(500).json({ message: "Failed to record payment" }); } finally { connection.release(); } };
const dashboardStats = async (req, res) => { try { const [[stats]] = await Promise.all([pool.query("SELECT (SELECT COUNT(*) FROM patients WHERE is_active = TRUE) AS active_patients, (SELECT COUNT(*) FROM doctors WHERE is_active = TRUE) AS doctors, (SELECT COUNT(*) FROM appointments WHERE appointment_date = CURRENT_DATE) AS todays_appointments, (SELECT COUNT(*) FROM beds WHERE status = 'Available') AS available_beds, (SELECT COUNT(*) FROM lab_orders WHERE status = 'Pending') AS pending_lab_orders, (SELECT COALESCE(SUM(outstanding_amount), 0) FROM bills WHERE outstanding_amount > 0) AS outstanding_bills, (SELECT COUNT(*) FROM medicine_batches WHERE quantity <= 10 AND expiry_date >= CURRENT_DATE) AS stock_alerts")]); const [appointments] = await pool.query("SELECT a.appointment_date, a.status, p.full_name AS patient_name, d.full_name AS doctor_name FROM appointments a JOIN patients p ON p.patient_id = a.patient_id JOIN doctors d ON d.doctor_id = a.doctor_id ORDER BY a.appointment_date DESC, a.appointment_time DESC LIMIT 8"); res.json({ stats, appointments }); } catch (error) { console.error("Dashboard stats error:", error); res.status(500).json({ message: "Failed to fetch dashboard statistics" }); } };

module.exports = { roles, doctorList, createDoctor, updateDoctor, deactivateDoctor, appointmentList, createAppointment, updateAppointmentStatus, createConsultation, updateConsultation, createMedicalRecord, prescriptionList, createPrescription, stockTransaction, admitPatient, dischargePatient, createBill, recordPayment, dashboardStats, list, getById, createSimple, updateSimple };