const express = require("express");
const authenticateToken = require("../middleware/authMiddleware");
const authorizeRoles = require("../middleware/roleMiddleware");
const controller = require("../controllers/hospitalController");

const router = express.Router();
const protect = (roles) => [authenticateToken, authorizeRoles(...roles)];
const route = (method, path, roles, handler) => router[method](path, ...protect(roles), handler);

route("get", "/dashboard", ["Admin"], controller.dashboardStats);
route("get", "/doctors", controller.roles.clinical, controller.doctorList);
route("get", "/doctors/:id", controller.roles.clinical, controller.getById("doctors", "doctor_id"));
route("post", "/doctors", controller.roles.admin, controller.createDoctor);
route("put", "/doctors/:id", controller.roles.admin, controller.updateDoctor);
route("delete", "/doctors/:id", controller.roles.admin, controller.deactivateDoctor);
route("get", "/appointments", controller.roles.clinical, controller.appointmentList);
route("get", "/appointments/:id", controller.roles.clinical, controller.getById("appointments", "appointment_id"));
route("post", "/appointments", ["Admin", "Doctor", "Receptionist"], controller.createAppointment);
route("put", "/appointments/:id", ["Admin", "Doctor", "Receptionist"], controller.updateAppointmentStatus);
route("get", "/consultations", ["Admin", "Doctor"], controller.list("consultations", "consultation_id", "*"));
route("get", "/consultations/:id", ["Admin", "Doctor"], controller.getById("consultations", "consultation_id"));
route("post", "/consultations", ["Admin", "Doctor"], controller.createConsultation);
route("put", "/consultations/:id", ["Admin", "Doctor"], controller.updateConsultation);
route("get", "/medical-records", ["Admin", "Doctor"], controller.list("medical_records", "record_id", "*"));
route("get", "/medical-records/:id", ["Admin", "Doctor"], controller.getById("medical_records", "record_id"));
route("post", "/medical-records", ["Admin", "Doctor"], controller.createMedicalRecord);
route("get", "/prescriptions", ["Admin", "Doctor", "Pharmacist"], controller.prescriptionList);
route("post", "/prescriptions", ["Admin", "Doctor"], controller.createPrescription);
route("get", "/medicines", ["Admin", "Doctor", "Pharmacist"], controller.list("medicines", "medicine_id", "*", ["name", "generic_name", "manufacturer", "category"]));
route("get", "/medicines/:id", ["Admin", "Doctor", "Pharmacist"], controller.getById("medicines", "medicine_id"));
route("post", "/medicines", controller.roles.pharmacy, controller.createSimple("medicines", ["name", "generic_name", "manufacturer", "category", "unit_price"], ["name"]));
route("put", "/medicines/:id", controller.roles.pharmacy, controller.updateSimple("medicines", "medicine_id", ["name", "generic_name", "manufacturer", "category", "unit_price", "is_active"]));
route("get", "/inventory", controller.roles.pharmacy, controller.list("medicine_batches", "batch_id", "*"));
route("post", "/inventory/batches", controller.roles.pharmacy, controller.createSimple("medicine_batches", ["medicine_id", "batch_number", "manufacture_date", "expiry_date", "quantity", "unit_price"], ["medicine_id", "batch_number", "expiry_date"]));
route("post", "/inventory/transactions", controller.roles.pharmacy, controller.stockTransaction);
route("get", "/lab-tests", ["Admin", "Doctor", "Lab Technician"], controller.list("lab_tests", "test_id", "*", ["name", "category"]));
route("post", "/lab-tests", controller.roles.admin, controller.createSimple("lab_tests", ["name", "category", "description", "price"], ["name"]));
route("put", "/lab-tests/:id", controller.roles.admin, controller.updateSimple("lab_tests", "test_id", ["name", "category", "description", "price"]));
route("get", "/lab-orders", ["Admin", "Doctor", "Lab Technician"], controller.list("lab_orders", "order_id", "*"));
route("post", "/lab-orders", ["Admin", "Doctor"], controller.createSimple("lab_orders", ["patient_id", "doctor_id", "test_id", "order_date", "status", "notes"], ["patient_id", "doctor_id", "test_id"]));
route("put", "/lab-orders/:id", ["Admin", "Lab Technician"], controller.updateSimple("lab_orders", "order_id", ["status", "notes"]));
route("post", "/lab-results", ["Admin", "Lab Technician"], controller.createSimple("lab_results", ["order_id", "technician_id", "result_value", "unit", "reference_range", "result_date", "remarks"], ["order_id", "technician_id", "result_value"]));
route("get", "/rooms", controller.roles.clinical, controller.list("rooms", "room_id", "*"));
route("post", "/rooms", controller.roles.admin, controller.createSimple("rooms", ["room_number", "room_type", "floor", "charges_per_day", "status"], ["room_number"]));
route("put", "/rooms/:id", controller.roles.admin, controller.updateSimple("rooms", "room_id", ["room_number", "room_type", "floor", "charges_per_day", "status"]));
route("get", "/beds", controller.roles.clinical, controller.list("beds", "bed_id", "*"));
route("post", "/beds", controller.roles.admin, controller.createSimple("beds", ["room_id", "bed_number", "status"], ["room_id", "bed_number"]));
route("put", "/beds/:id", controller.roles.admin, controller.updateSimple("beds", "bed_id", ["room_id", "bed_number", "status"]));
route("get", "/admissions", controller.roles.clinical, controller.list("admissions", "admission_id", "*"));
route("post", "/admissions", ["Admin", "Receptionist"], controller.admitPatient);
route("post", "/admissions/:id/discharge", ["Admin", "Receptionist"], controller.dischargePatient);
route("get", "/bills", ["Admin", "Receptionist"], controller.list("bills", "bill_id", "*"));
route("post", "/bills", ["Admin", "Receptionist"], controller.createBill);
route("post", "/bills/:id/payments", ["Admin", "Receptionist"], controller.recordPayment);
route("get", "/payments", ["Admin", "Receptionist"], controller.list("payments", "payment_id", "*"));

module.exports = router;