const API_ROOT = "http://localhost:5000/api";
const operationsUser = requireLogin();
const role = operationsUser ? operationsUser.role : "";
const modules = {
    departments: { title: "Departments", endpoint: "/departments", roles: ["Admin", "Doctor", "Receptionist"], columns: ["department_id", "name", "description"], fields: [{ name: "name", label: "Name", required: true }, { name: "description", label: "Description" }] },
    doctors: { title: "Doctors", endpoint: "/doctors", roles: ["Admin", "Doctor", "Receptionist"], columns: ["doctor_id", "full_name", "specialization", "department_name", "phone"], fields: [{ name: "username", label: "Username", required: true }, { name: "password", label: "Temporary password", type: "password", required: true }, { name: "full_name", label: "Full name", required: true }, { name: "specialization", label: "Specialization" }, { name: "department_id", label: "Department ID", type: "number", required: true }, { name: "phone", label: "Phone" }, { name: "email", label: "Email", type: "email" }] },
    appointments: { title: "Appointments", endpoint: "/appointments", roles: ["Admin", "Doctor", "Receptionist"], columns: ["appointment_id", "patient_name", "doctor_name", "appointment_date", "appointment_time", "status"], fields: [{ name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "doctor_id", label: "Doctor ID", type: "number", required: true }, { name: "appointment_date", label: "Date", type: "date", required: true }, { name: "appointment_time", label: "Time", type: "time", required: true }, { name: "reason", label: "Reason" }] },
    medicines: { title: "Medicines", endpoint: "/medicines", roles: ["Admin", "Doctor", "Pharmacist"], columns: ["medicine_id", "name", "generic_name", "manufacturer", "category", "unit_price"], fields: [{ name: "name", label: "Name", required: true }, { name: "generic_name", label: "Generic name" }, { name: "manufacturer", label: "Manufacturer" }, { name: "category", label: "Category" }, { name: "unit_price", label: "Unit price", type: "number", step: "0.01" }] },
    inventory: { title: "Inventory batches", endpoint: "/inventory", dataKey: "medicine_batches", columns: ["batch_id", "medicine_id", "batch_number", "expiry_date", "quantity", "unit_price"], fields: [{ name: "medicine_id", label: "Medicine ID", type: "number", required: true }, { name: "batch_number", label: "Batch number", required: true }, { name: "manufacture_date", label: "Manufacture date", type: "date" }, { name: "expiry_date", label: "Expiry date", type: "date", required: true }, { name: "quantity", label: "Opening quantity", type: "number" }, { name: "unit_price", label: "Unit price", type: "number", step: "0.01" }] },
    "lab-tests": { title: "Lab tests", endpoint: "/lab-tests", roles: ["Admin", "Doctor", "Lab Technician"], columns: ["test_id", "name", "category", "price"], fields: [{ name: "name", label: "Name", required: true }, { name: "category", label: "Category" }, { name: "description", label: "Description" }, { name: "price", label: "Price", type: "number", step: "0.01" }] },
    "lab-orders": { title: "Lab orders", endpoint: "/lab-orders", roles: ["Admin", "Doctor", "Lab Technician"], columns: ["order_id", "patient_id", "doctor_id", "test_id", "order_date", "status"], fields: [{ name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "doctor_id", label: "Doctor ID", type: "number", required: true }, { name: "test_id", label: "Test ID", type: "number", required: true }, { name: "order_date", label: "Order date", type: "date" }, { name: "status", label: "Status", value: "Pending" }, { name: "notes", label: "Notes" }] },
    consultations: { title: "Consultations", endpoint: "/consultations", roles: ["Admin", "Doctor"], columns: ["consultation_id", "appointment_id", "patient_id", "doctor_id", "consultation_date", "diagnosis"], fields: [{ name: "appointment_id", label: "Appointment ID", type: "number" }, { name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "doctor_id", label: "Doctor ID", type: "number", required: true }, { name: "consultation_date", label: "Date", type: "date" }, { name: "diagnosis", label: "Diagnosis", required: true }, { name: "notes", label: "Notes" }] },
    "medical-records": { title: "Medical records", endpoint: "/medical-records", roles: ["Admin", "Doctor"], columns: ["record_id", "patient_id", "doctor_id", "consultation_id", "visit_date", "vital_signs"], fields: [{ name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "doctor_id", label: "Doctor ID", type: "number", required: true }, { name: "consultation_id", label: "Consultation ID", type: "number" }, { name: "visit_date", label: "Visit date", type: "date" }, { name: "notes", label: "Notes" }, { name: "vital_signs", label: "Vital signs" }] },
    prescriptions: { title: "Prescriptions", endpoint: "/prescriptions", roles: ["Admin", "Doctor", "Pharmacist"], dataKey: "prescriptions", columns: ["prescription_id", "patient_name", "doctor_name", "prescription_date", "diagnosis"], fields: [{ name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "doctor_id", label: "Doctor ID", type: "number", required: true }, { name: "consultation_id", label: "Consultation ID", type: "number" }, { name: "diagnosis", label: "Diagnosis" }, { name: "notes", label: "Notes" }, { name: "items", label: "Medicine items JSON", value: "[]", required: true }] },
    rooms: { title: "Rooms", endpoint: "/rooms", columns: ["room_id", "room_number", "room_type", "floor", "charges_per_day", "status"], fields: [{ name: "room_number", label: "Room number", required: true }, { name: "room_type", label: "Room type" }, { name: "floor", label: "Floor", type: "number" }, { name: "charges_per_day", label: "Daily charge", type: "number", step: "0.01" }, { name: "status", label: "Status", value: "Available" }] },
    beds: { title: "Beds", endpoint: "/beds", columns: ["bed_id", "room_id", "bed_number", "status"], fields: [{ name: "room_id", label: "Room ID", type: "number", required: true }, { name: "bed_number", label: "Bed number", required: true }, { name: "status", label: "Status", value: "Available" }] },
    admissions: { title: "Admissions", endpoint: "/admissions", columns: ["admission_id", "patient_id", "doctor_id", "room_id", "bed_id", "status"], fields: [{ name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "doctor_id", label: "Doctor ID", type: "number", required: true }, { name: "department_id", label: "Department ID", type: "number", required: true }, { name: "room_id", label: "Room ID", type: "number", required: true }, { name: "bed_id", label: "Available bed ID", type: "number", required: true }, { name: "admission_date", label: "Admission date", type: "datetime-local" }, { name: "reason", label: "Reason" }] },
    bills: { title: "Bills", endpoint: "/bills", columns: ["bill_id", "patient_id", "admission_id", "bill_date", "total_amount", "status", "outstanding_amount"], fields: [{ name: "patient_id", label: "Patient ID", type: "number", required: true }, { name: "admission_id", label: "Admission ID", type: "number" }, { name: "description", label: "Item description", required: true }, { name: "quantity", label: "Quantity", type: "number", value: "1", required: true }, { name: "unit_price", label: "Unit price", type: "number", step: "0.01", required: true }] }
};
const allowed = Object.entries(modules).filter(([, config]) => config.roles.includes(role));
let currentModule = new URLSearchParams(window.location.search).get("module") || (allowed[0] && allowed[0][0]);

function showMessage(text, type = "info") { const element = document.getElementById("operationsMessage"); element.className = `alert alert-${type}`; element.textContent = text; }
function currentConfig() { return modules[currentModule]; }
function dataKey(config) { return config.dataKey || config.endpoint.slice(1); }
function renderNavigation() { const nav = document.getElementById("operationsNav"); nav.innerHTML = ""; allowed.forEach(([key, config]) => { const link = document.createElement("a"); link.className = `nav-link ${key === currentModule ? "active" : ""}`; link.href = `operations.html?module=${key}`; link.textContent = config.title; nav.appendChild(link); }); }
function renderFields(config) { const container = document.getElementById("recordFields"); container.innerHTML = ""; config.fields.forEach(field => { const wrapper = document.createElement("div"); wrapper.className = "col-md-6"; const label = document.createElement("label"); label.className = "form-label fw-semibold"; label.htmlFor = `field-${field.name}`; label.textContent = field.label; const input = document.createElement("input"); input.className = "form-control"; input.id = `field-${field.name}`; input.name = field.name; input.type = field.type || "text"; input.required = Boolean(field.required); if (field.step) input.step = field.step; if (field.value !== undefined) input.value = field.value; wrapper.append(label, input); container.appendChild(wrapper); }); }
function renderTable(rows, config) { const head = document.getElementById("recordsHead"); const body = document.getElementById("recordsBody"); head.innerHTML = `<tr>${config.columns.map(column => `<th>${column.replaceAll("_", " ")}</th>`).join("")}</tr>`; body.innerHTML = ""; if (!rows.length) { body.innerHTML = `<tr><td colspan="${config.columns.length}" class="text-center text-secondary py-4">No records found.</td></tr>`; return; } rows.forEach(row => { const tr = document.createElement("tr"); config.columns.forEach(column => { const td = document.createElement("td"); td.textContent = row[column] ?? "-"; tr.appendChild(td); }); body.appendChild(tr); }); }
async function loadRecords() { const config = currentConfig(); if (!config) return; document.getElementById("recordsBody").innerHTML = `<tr><td colspan="8" class="text-center py-4">Loading records...</td></tr>`; const search = document.getElementById("operationsSearch").value.trim(); const url = `${API_ROOT}${config.endpoint}${search ? `?search=${encodeURIComponent(search)}` : ""}`; try { const response = await fetchWithAuth(url); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load records"); const rows = data[dataKey(config)] || data.departments || []; document.getElementById("recordsCount").textContent = `${data.count || rows.length} record(s)`; renderTable(rows, config); } catch (error) { showMessage(error.message, "danger"); renderTable([], config); } }
function setupModule() { const config = currentConfig(); if (!config) return; document.getElementById("operationsTitle").textContent = config.title; document.getElementById("recordsHeading").textContent = config.title; document.getElementById("operationsRole").textContent = role; renderNavigation(); renderFields(config); loadRecords(); }
document.getElementById("refreshOperations").addEventListener("click", loadRecords);
document.getElementById("operationsSearch").addEventListener("keydown", event => { if (event.key === "Enter") loadRecords(); });
document.getElementById("newRecordButton").addEventListener("click", () => { document.getElementById("recordFormCard").classList.remove("d-none"); document.getElementById("recordFormTitle").textContent = `New ${currentConfig().title.slice(0, -1)}`; });
document.getElementById("cancelRecord").addEventListener("click", () => document.getElementById("recordFormCard").classList.add("d-none"));
document.getElementById("recordForm").addEventListener("submit", async event => { event.preventDefault(); const config = currentConfig(); const payload = Object.fromEntries(new FormData(event.target).entries()); if (currentModule === "bills") payload.items = [{ service_type: "Other", description: payload.description, quantity: Number(payload.quantity), unit_price: Number(payload.unit_price) }]; if (currentModule === "prescriptions") { try { payload.items = JSON.parse(payload.items); } catch { showMessage("Medicine items must be valid JSON.", "danger"); return; } } try { const response = await fetchWithAuth(`${API_ROOT}${config.endpoint}`, { method: "POST", body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to save record"); showMessage(data.message || "Record saved", "success"); event.target.reset(); document.getElementById("recordFormCard").classList.add("d-none"); await loadRecords(); } catch (error) { showMessage(error.message, "danger"); } });
setupModule();